"""migrate extracted fields to user table

Revision ID: 16463be9b530
Revises: a026107d2724
Create Date: 2026-01-29 15:12:11.105607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16463be9b530'
down_revision: Union[str, None] = 'a026107d2724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_pg_collection')
    op.drop_table('langchain_pg_embedding')
    op.drop_column('portfolios', 'extracted_job_title')
    op.drop_column('portfolios', 'extracted_summary')
    op.add_column('users', sa.Column('profile_summary', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('desired_job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'desired_job_title')
    op.drop_column('users', 'profile_summary')
    op.add_column('portfolios', sa.Column('extracted_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('extracted_job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='langchain_pg_embedding_pkey')
    )
    op.create_table('langchain_pg_collection',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    sa.UniqueConstraint('name', name='langchain_pg_collection_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
