"""migrate extracted fields to user table

Revision ID: 16463be9b530
Revises: a026107d2724
Create Date: 2026-01-29 15:12:11.105607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16463be9b530'
down_revision: Union[str, None] = 'a026107d2724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip langchain table drops - they have foreign key dependencies
    op.drop_column('portfolios', 'extracted_job_title')
    op.drop_column('portfolios', 'extracted_summary')
    op.add_column('users', sa.Column('profile_summary', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('desired_job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'desired_job_title')
    op.drop_column('users', 'profile_summary')
    op.add_column('portfolios', sa.Column('extracted_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('extracted_job_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
