"""add_score_column_to_recommendation

Revision ID: 4cc871699003
Revises: 29e06c94483c
Create Date: 2026-01-30 00:17:36.891654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc871699003'
down_revision: Union[str, None] = '29e06c94483c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'score')
    # ### end Alembic commands ###
