"""Refine_CoverLetter_and_add_CoverLetterItem

Revision ID: 556fe6422ead
Revises: 4cc871699003
Create Date: 2026-01-30 02:53:38.984117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556fe6422ead'
down_revision: Union[str, None] = '4cc871699003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_letter_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('suggested_improvements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letter_items_id'), 'cover_letter_items', ['id'], unique=False)
    op.add_column('cover_letters', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True))
    op.add_column('cover_letters', sa.Column('gap_analysis', sa.JSON(), nullable=True))
    op.add_column('cover_letters', sa.Column('job_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cover_letters', 'job_analysis')
    op.drop_column('cover_letters', 'gap_analysis')
    op.drop_column('cover_letters', 'status')
    op.drop_index(op.f('ix_cover_letter_items_id'), table_name='cover_letter_items')
    op.drop_table('cover_letter_items')
    # ### end Alembic commands ###
