"""Expand recruitment schema

Revision ID: a026107d2724
Revises: 87c72146183b
Create Date: 2026-01-29 10:39:42.328512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a026107d2724'
down_revision: Union[str, None] = '87c72146183b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruitments', sa.Column('link', sa.String(), nullable=True))
    op.add_column('recruitments', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('recruitments', sa.Column('education', sa.String(), nullable=True))
    op.add_column('recruitments', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('recruitments', sa.Column('salary', sa.String(), nullable=True))
    op.add_column('recruitments', sa.Column('job_sector', sa.String(), nullable=True))
    op.add_column('recruitments', sa.Column('key_responsibilities', sa.Text(), nullable=True))
    op.add_column('recruitments', sa.Column('required_qualifications', sa.Text(), nullable=True))
    op.add_column('recruitments', sa.Column('preferred_qualifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruitments', 'preferred_qualifications')
    op.drop_column('recruitments', 'required_qualifications')
    op.drop_column('recruitments', 'key_responsibilities')
    op.drop_column('recruitments', 'job_sector')
    op.drop_column('recruitments', 'salary')
    op.drop_column('recruitments', 'employment_type')
    op.drop_column('recruitments', 'education')
    op.drop_column('recruitments', 'experience')
    op.drop_column('recruitments', 'link')
    # ### end Alembic commands ###
